version: '3.8'

services:
  kob_frontend:
    container_name: kob_frontend
    image: habor.rvvcs.com/revelsoft/auth-km-kob-frontend:v1.01
    environment:
      - TZ=Asia/Bangkok
    restart: always
    ports:
      - 3004:3000
    command: npm run start


networks:
  app-network:
    driver: bridge


